#ifndef DEARIMXML_IMGUIENUM_H
#define DEARIMXML_IMGUIENUM_H

namespace ImXML {
	enum ImGuiEnum {
		BEGIN, PLACEHOLDER, BUTTON, TEXT, SAMELINE, MENUBAR, MENU, MENUITEM, SLIDERFLOAT, INPUTTEXT, 
		TREENODE, TREE, COLUMNS, COLUMN, GROUP, COLORPICKER3, COLORPICKER4, COLOREDIT3, COLOREDIT4,
	};
}

#endif /* DEARIMXML_IMGUIENUM_H */
