#ifndef IMGUIENUM_H
#define IMGUIENUM_H

namespace ImXML {
	enum ImGuiEnum {
		BEGIN, PLACEHOLDER, BUTTON, TEXT, SAMELINE, MENUBAR, MENU, MENUITEM, SLIDERFLOAT, INPUTTEXT, 
		TREENODE, TREE, TABLE, ROW, COLUMN, GROUP, COLORPICKER3, COLORPICKER4, COLOREDIT3, COLOREDIT4,
		POPUPCONTEXTWINDOW, SEPARATOR,
	};
}

#endif /* IMGUIENUM_H */
