#ifndef DEARIMXML_IMGUIENUM_H
#define DEARIMXML_IMGUIENUM_H

namespace ImXML {
	enum ImGuiEnum {
		BEGIN, PLACEHOLDER, BUTTON, TEXT, SAMELINE, MENUBAR, MENU, MENUITEM, SLIDERFLOAT, INPUTTEXT, TREENODE, TREE,
	};
}

#endif /* DEARIMXML_IMGUIENUM_H */
